### ISSUE TITLE
Missing Dog Mesh

### ISSUE THREAD

**Issue by retrophil** [Unity-Technologies/EndlessRunnerSampleGame#1]
ObstacleDog is missing it's mesh

**Comment by UnityGuillaume** [comment]
Since the repo is a direct push from our internal repo, I totally forgot it use git LFS (Large File Support), so without git lfs installed, a couple of fbx won't be downloaded, including the dog fbx file! (see here to install git lfs, once `git lfs install` is run, you can clone and it should work as expected : https://git-lfs.github.com/)

Thanks for thereport, I'll add a note on the readme about the need to have git lfs installed!
