### ISSUE TITLE
2019.1.0b10 Game launches to entirely white screen

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/EndlessRunnerSampleGame#5]
Go into the Start Scene and proceed through like you would normally to start a new game

When you get to playing the game you'll notice that the entire screen except for the UI is blank (white)
The countdown still occurs and your character starts running, collecting pickups, etc.

https://gyazo.com/a1a6e2a31678d26be2488e64e8a6ca15

**Comment by UnityGuillaume** [comment]
Was caused by lightweight not allowing to clear only depth on camera anymore. Fixed by updating the lightweight rendering pipeline to be able to use Render Pass to do everything in a signle camera, so keep an eye for rendering glitch.

Done on the addressable branch (see commit linked in that issue)

**Comment by Jacekpapapolski** [comment]
Fixed in 7dc2fd5 - Closing!
